version: 1.{build}

os: Visual Studio 2015

branches:
  only:
  - develop

nuget:
  account_feed: true
  disable_publish_on_pr: true

install:
  - ps: |
      $joined = (GitVersion) -join "`n"
      $versionInfo = ($joined | ConvertFrom-Json).NuGetVersionV2
      Update-AppveyorBuild -Version $versionInfo

before_build:
  - cmd: dnvm update-self
  - cmd: dnvm upgrade
  - cmd: dnu restore

build_script:
  - cmd: dnu pack Bdb.Specs --configuration Release --out artifacts

artifacts:
  - path: artifacts\**\*.nupkg