version: {branch}.{build}

os: Visual Studio 2015

branches:
  only:
  - develop

nuget:
  account_feed: true
  disable_publish_on_pr: true

before_build:
  - cmd: dnvm update-self
  - cmd: dnvm upgrade
  - cmd: dnu restore
  
build_script:
  - cmd: dnu pack Bdb.Specs