version: 1.{build}

os: Visual Studio 2015

branches:
  only:
  - develop
  - master

install:
  - ps: |
      $joined = (GitVersion) -join "`n"
      $versionInfo = ($joined | ConvertFrom-Json).NuGetVersionV2
      $json = Get-Content -Raw -Path "Bdb.Specs\project.json" | ConvertFrom-Json
      $json.version = $versionInfo
      $json | ConvertTo-Json -depth 999 | Out-File "Bdb.Specs\project.json"
      Update-AppveyorBuild -Version $versionInfo

before_build:
  - cmd: dnvm update-self
  - cmd: dnvm upgrade
  - cmd: dnu restore

build_script:
  - cmd: dnu pack Bdb.Specs --configuration Release --out artifacts

test: off

artifacts:
  - path: artifacts\**\*.nupkg

deploy:
  provider: NuGet
  server: https://www.myget.org/F/boodaba/api/v2/package
  api_key:
    secure: 42Sy0b4tDVm3kK2BDlrHXoez+zyVC9/TzM85efCjeSFjWRY/Nn9Rx7NlNewlvPK+
  skip_symbols: false
  symbol_server: https://www.myget.org/F/boodaba/api/v2/package
