version: 1.{build}

os: Visual Studio 2015

branches:
  only:
  - develop
  - master

install:
  - ps: |
      $joined = (GitVersion) -join "`n"
      $versionInfo = ($joined | ConvertFrom-Json).NuGetVersionV2
      $json = Get-Content -Raw -Path "Bdb.Specs\project.json" | ConvertFrom-Json
      $json.version = $versionInfo
      $json | ConvertTo-Json -depth 999 | Out-File "Bdb.Specs\project.json"
      Update-AppveyorBuild -Version $versionInfo

before_build:
  - cmd: dnvm update-self
  - cmd: dnvm upgrade
  - cmd: dnu restore

build_script:
  - cmd: dnu pack Bdb.Specs --configuration Release --out artifacts

test: off

artifacts:
  - path: artifacts\**\*.nupkg

deploy:
  provider: NuGet
  server: https://www.myget.org/F/boodaba/api/v2/package
  api_key:
    secure: qyfJ610MxvoFG6yZTtu9okDIHEokqk603wX4Hw41pnLLu5zd02oPmAZXj71Rwb/L
  skip_symbols: false
  symbol_server:
    secure: hEkcKLtbQT5DcVgUUOjtFC4Y1EsaS3FsZRU3Nu8PxMAivDWFg6XBEMlO4GCaO9qMhIJ983StftbGMjGB8zvgPUfbSWAuTINhWZrb/VkKxl6ePnFZ+94+DzAsLouxuy6N
